/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ClearingRouteImport } from './routes/clearing'
import { Route as IndexRouteImport } from './routes/index'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearingRoute = ClearingRouteImport.update({
  id: '/clearing',
  path: '/clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clearing': typeof ClearingRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clearing': typeof ClearingRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clearing': typeof ClearingRoute
  '/daily': typeof DailyRoute
  '/expenses': typeof ExpensesRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clearing'
    | '/daily'
    | '/expenses'
    | '/settings'
    | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clearing' | '/daily' | '/expenses' | '/settings' | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/clearing'
    | '/daily'
    | '/expenses'
    | '/settings'
    | '/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClearingRoute: typeof ClearingRoute
  DailyRoute: typeof DailyRoute
  ExpensesRoute: typeof ExpensesRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearing': {
      id: '/clearing'
      path: '/clearing'
      fullPath: '/clearing'
      preLoaderRoute: typeof ClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClearingRoute: ClearingRoute,
  DailyRoute: DailyRoute,
  ExpensesRoute: ExpensesRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
